---
- name: named config
  hosts: all
  tasks:
  - name: Check if the file contains the entry
    shell: cat /etc/named.conf | grep "mol.gov.om."
    become: yes
    become_method: sudo
    failed_when: false
    register: grep_result
  - name:
    lineinfile:
      dest: /etc/named.conf
      insertafter: "};"
      line: "\nzone 'mol.gov.om.' IN {\n\tforward only;\n\ttype forward;\n\tforwarders {10.99.7.11; 10.99.7.13; };\n};\n"
      state: present
      backup: yes
    when: grep_result.rc > 0
