---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check if oracle linux is installed
      command:  cat /etc/os-release | grep -Ei "ID=|VERSION_ID"
      register: os_name
      ignore_errors: yes
    - debug:
        msg: "{{ os_name.stdout }}"
    - name: Check the kernal version
      shell: |
        uname -r | cut -c -7
      register: kernal_ver
      ignore_errors: yes
    - debug:
        msg: "{{ kernal_ver.stdout }}"
