---
##AP##
- name: Create Oracle Home Directory
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - dir_list.yml
  tasks:
    - name: Create Oracle Home Directory
      file:
        path: /home/"{{ item }}"
        state: directory
        owner: "{{ oracle_user }}"
        group: "{{ oracle_group }}"
      with_items: "{{ directory }}"
      register: perm_reggit 
    
    - name: output verify
      debug:
        msg: "{{ perm_reggit.stdout }}"
      when: perm_reggit.changed
      
