---
##AP##
- name: sysctl configuration 
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Check if the file contains the entry
    shell: cat /etc/sysctl.conf | grep "kernel.shmall = 4294967296"
    failed_when: false
    register: grep_result
  - name: Editing sysctl_conf
    blockinfile:
      path: /etc/sysctl.conf
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        kernel.shmall = 4294967296
        kernel.shmmni = 4096
        kernel.sem = 250 32000 100 128
        net.ipv4.ip_local_port_range = 9000 65500
        net.core.rmem_default = 4194304
        net.core.rmem_max = 4194304
        net.core.wmem_default = 262144
        net.core.wmem_max = 1048576
        fs.file-max = 6815744
        fs.aio-max-nr = 6815744
      backup: yes
    when: grep_result.rc > 0
  - name: sysctl make it permanent
      shell: |
        sysctl -p
      register: sys_pem
      ignore_errors: yes
    - debug:
        msg: "{{ sys_pem.stdout }}"
      when: grep_result.rc > 0
#  - name: sysctl
#    sysctl:
#      sysctl_set: true
#      reload: true
#    when: grep_result.rc > 0
